# Generated by Django 6.0.4 on 2026-04-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PROSPECCAO', 'Garimpo'), ('CONTATO', 'Primeiro Contato'), ('BRIEFING', 'Reunião/Briefing'), ('PROPOSTA', 'Proposta Enviada'), ('FECHADO', 'Contrato Assinado'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('link_google_maps', models.URLField(blank=True)),
                ('ultima_interacao', models.DateTimeField(auto_now=True)),
                ('proximo_contato', models.DateField(blank=True, null=True)),
                ('tem_site', models.BooleanField(default=False)),
                ('nota_performance', models.IntegerField(blank=True, null=True)),
                ('tem_pixel', models.BooleanField(default=False)),
                ('nota_google_meu_negocio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project', serialize=False, to='crm.lead')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('link_figma', models.URLField(blank=True)),
                ('link_github', models.URLField(blank=True)),
                ('credenciais_info', models.TextField(blank=True, help_text='Cuidado: Não guarde senhas puras aqui. Use um gestor de senhas.')),
                ('dominio_registrado', models.BooleanField(default=False)),
                ('setup_servidor', models.BooleanField(default=False)),
                ('design_aprovado', models.BooleanField(default=False)),
                ('copywriting_finalizado', models.BooleanField(default=False)),
                ('go_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_vencimento', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
        ),
    ]
