# Generated by Django 6.0.4 on 2026-04-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nicho',
            field=models.CharField(choices=[('RESTAURANTE', 'Restaurantes & Lanchonetes'), ('ESTETICA', 'Salões & Estética'), ('SERVICOS', 'Prestadores de Serviço'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
