# Generated by Django 6.0.4 on 2026-04-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_nicho'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='valor_recorrente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
