# Generated by Django 6.0.4 on 2026-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_notas_project_valor_recorrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='nicho',
            field=models.CharField(default='Outros', max_length=100),
        ),
    ]
