# Generated by Django 6.0.4 on 2026-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_nicho'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
