# Generated by Django 4.2.30 on 2026-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ga4_property_id',
            field=models.CharField(blank=True, help_text='ID da propriedade do Google Analytics 4 (apenas números, ex: 534388123)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
