# Generated by Django 4.2.30 on 2026-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_lead_ga4_property_id_alter_interaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='motivo_espera',
            field=models.TextField(blank=True, default='', help_text='Motivo pelo qual o lead está aguardando o cliente'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PROSPECCAO', 'Garimpo'), ('CONTATO', 'Primeiro Contato'), ('BRIEFING', 'Reunião/Briefing'), ('PROPOSTA', 'Proposta Enviada'), ('AGUARDANDO', 'Aguardando Cliente'), ('FECHADO', 'Contrato Assinado'), ('PERDIDO', 'Perdido')], default='PROSPECCAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
